version: "4.0.0"
name: "Yggdrasil"

quality:
  min_artifact_length: 50
  max_direct_relations: 10
  context_budget:
    warning: 10000
    error: 20000

parallel: 10
debug: true

reviewer:
  verify_aspects: true
  verify_artifacts: true
  consensus: 1
  claude-code:
    model: haiku
