// The absolutes the wording policy (absolute-wording.test.ts) accepts without a
// claim test: each was read against the code and holds at every edge, and each
// entry names a phrase of its sentence and why. Written by review, one entry per
// sentence; a sentence that stops being true is reworded, not kept here. Reads
// nothing and writes nothing.

import type { ReviewedAbsolute } from './absolute-wording.js';

export const REVIEWED_ABSOLUTES: ReviewedAbsolute[] = [
  // README.md
  { phrase: 'install it day zero for a soft, draft-only law that never blocks', why: 'A claim about Grain, not the yg CLI; Grain\'s own README (\'What it costs you\': \'It never blocks: no gate, no failing build, no policy file\') holds the same promise.' },
  // docs/aspect-status.md
  { phrase: 'it never changes a verdict\'s input hash', why: 'core/pair-hash.ts excludes status from every hash ingredient (header \'status — rendering only\'), held by tests/e2e/cli-aspect-status-extended.test.ts \'E7: a bare enforced->advisory status flip does NOT invalidate the verdict\'.' },
  { phrase: 'through `implies`, propagates nothing at all', why: 'core/graph/aspects.ts skips implies propagation when the implier\'s status is draft (statuses.get(id) !== \'draft\'; implierStatus === \'draft\' continue), held by tests/integration/aspect-status-implies.test.ts \'A at draft: implies do not propagate\'.' },
  { phrase: 'while an advisory refusal never blocks closure', why: 'core/fill-closure.ts applyPositiveClosure filters to vp.pair.status === \'enforced\' before requiring every pair settled, so advisory pairs never enter the closure condition.' },
  { phrase: '**advisory never blocks** (whether a pair is refused or merely unverified', why: 'core/check-pair-issues.ts gives refused/unverified/companion-error pairs \'enforced ? error : warning\' and checkReviewerPresence uses the strictest status; the one status-independent error, prompt-too-large, is named as the exception in this same sentence.' },
  { phrase: 'when the aspect is `draft`, the hook never runs', why: 'core/pairs.ts drops effective-draft pairs (if (!includeDraft && effectiveStatus === \'draft\') continue) so the fill never sizes or fills them, held by tests/e2e/cli-llm-companion-integration.test.ts \'(+draft) a draft companion aspect never runs the hook\'.' },
  { phrase: 'Costs nothing. - `status=draft` → aspect applies but produces no expected pair', why: 'A when-false aspect is filtered out before any pair exists (core/pairs.ts cascade drop \'when-not-satisfied\'), so no check.mjs runs and no reviewer is called for it.' },
  // docs/aspects.md
  { phrase: 'it never blocks a build, never changes a verdict', why: 'core/checks/aspect-contracts.ts checkReviewOverdue always emits severity \'warning\' and only reads aspect.reviewBy; review_by is not a hash ingredient (core/pair-hash.ts).' },
  { phrase: 'the false-block number never blocks a build', why: 'The fp signal is rendered only by cli/aspects.ts --health; advise\'s decorative-rule nomination (core/advise-nominations.ts) uses catch/exposure, not fp, and no command changes a rule\'s status.' },
  // docs/cli-reference.md
  { phrase: 'so a count never reads as the number of blocks under it', why: 'formatters/check-render-views.ts formatOutput always passes the whole run\'s blockCount to renderHeader (formatters/check-render-header.ts), whose inBlocks appends \'in N blocks\' whenever findings and blocks differ.' },
  { phrase: 'always the whole run\'s, so a shortened report never reads as', why: 'formatters/check-render-views.ts formatOutput counts errors/warnings from the full result.issues before any view narrows the body, and cli/check.ts passes the full result with the view.' },
  { phrase: 'pure attention: never an issue, never an exit code, never a suggested next step', why: 'core/feature-index-write.ts writeFeatureIndex wraps compute and write in try/catch (debugWrite only) and core/check.ts runCheck calls it after issues are assembled, using only skippedNotIgnored for a note.' },
  { phrase: '`yg check` only **warns** (never blocks) when the dates fall out of order', why: 'core/checks/incident-ledger.ts checkIncidentLedger emits only severity \'warning\' and io/incidents-store.ts readIncidents returns no entries for a missing file; tests/e2e/cli-incident-ledger.test.ts \'2. two DESCENDING datetimes → exactly ONE non-blocking warning; yg check stays exit 0\'.' },
  { phrase: '`yg incident` never touches the lock.', why: 'cli/incident.ts and io/incidents-store.ts import no lock-store and write only incidents.md (appendIncident).' },
  { phrase: 'it never runs the whole-project relation pass or verifies pairs against the lock', why: 'cli/owner.ts resolveOneOwnerForBatch/resolveOwnersBatch never call runProjectRelationPass or readLock, and OwnerBatchEntry has no enforced field.' },
  { phrase: 'Run an aspect of either kind on demand; never writes the lock', why: 'cli/aspect-test.ts and the core modules it imports (pairs, tier-selection, pair-inputs, companion-resolve, aspect-test-file-target) import no lock-store; its only write is the diag event via appendVerdictEvent.' },
  { phrase: 'it exits `0` whatever it finds, never writes the lock', why: 'cli/simulate.ts runSimulation returns 0 for every completed report (non-zero only on real-repo preconditions) and imports no lock-store.' },
  { phrase: 'It never touches the lock. - **`lock`** merges a committed lock file per key', why: 'cli/merge-driver.ts runMergeDriver\'s log branch writes only oursPath (the log.md) via mergeLogTexts; only the lock kind calls mergeLockTexts.' },
  { phrase: 'It never fails the merge; it leaves the lock files modified', why: 'cli/init-scaffold.ts writes the post-merge hook as merge-resolve \'|| echo …\' followed by \'exit 0\', and git runs post-merge only after the merge completed.' },
  { phrase: '`--dry-run` answers all of the above and writes nothing at all.', why: 'cli/adopt.ts returns from the dryRun branch before its first write (initDebugLog, gitignore, move, logAdd, runFill all follow); tests/e2e/cli-adopt.test.ts \'5: --dry-run reports the same facts and writes nothing at all\'.' },
  { phrase: 'Never blocks and never writes a verdict. | Ask the user', why: 'generated from source/cli/src/utils/issue-code-registry.ts (issue-codes region of docs/cli-reference.md); not edited here.' },
  { phrase: 'A valid refused verdict on an advisory pair — reported, never blocks.', why: 'generated from source/cli/src/utils/issue-code-registry.ts (issue-codes region of docs/cli-reference.md); not edited here.' },
  { phrase: '`package-drills-missing` | error | A published rule has no drill cases', why: 'generated from source/cli/src/utils/issue-code-registry.ts (issue-codes region of docs/cli-reference.md); not edited here.' },
  // docs/concurrency.md
  { phrase: 'naming the process that holds the lock, and changes nothing', why: 'io/package-store.ts acquirePackCommandLock throws PackCommandBusyError before withCommandLock (cli/pack-source.ts) runs the body or the staging sweep; the only code before it is argument parsing and graph loading.' },
  // docs/conditional-aspects.md
  { phrase: 'It never blocks, because two legitimate shapes look identical', why: 'core/checks/aspects.ts emits when-unmatched-port as severity \'warning\' and keeps it out of STRUCTURAL_CODES (issue-code-registry.ts severity \'warning\').' },
  // docs/configuration.md
  { phrase: 'It never reads `OPENAI_API_KEY`: the endpoint can be any server', why: 'llm/api-utils.ts resolveApiKey maps openai-compatible only to OPENAI_COMPATIBLE_API_KEY (ENV_VAR_MAP), held by tests/unit/llm/openai.test.ts \'never sends OPENAI_API_KEY to an openai-compatible endpoint\'.' },
  { phrase: '`yg init` never writes a key it read from the environment', why: 'cli/init-reviewer-setup.ts returns apiKey undefined when promptApiKey reports fromEnv, and the non-interactive path returns only keyEnvVar, so reconcileSecretsKey never receives an environment key.' },
  { phrase: 'as they do for any file type-level coverage never touches', why: 'A definitional clause naming files outside type-level coverage, not a claim about a CLI effect; with coverage.type_level off the type-coverage classification is not computed (core/type-coverage.ts).' },
  { phrase: 'The check is deterministic and costs nothing; script pairs have no prompt', why: 'core/verify-lock.ts measures the assembled prompt without any provider call, and deterministic pairs are classified with gate undefined (\'Deterministic pairs have no prompt and are not subject to the gate\').' },
  { phrase: 'or a block that names nothing at all (`progressive: {}`) is a hard', why: 'io/config-parser.ts rejects an empty progressive mapping (\'progressive is present but names no reference\') and unknown keys (config-progressive-unknown-key), and reads the block from the committed file only.' },
  { phrase: 'The note is purely advisory: it never blocks a check', why: 'signals.attention only gates the note in cli/build-context.ts and the deviation count in cli/advise.ts; the feature index is never an issue or hash input (core/feature-index-write.ts header).' },
  { phrase: 'Turning the opt-in on or off never changes any verification result', why: 'events.committed_llm is read only by core/fill-writer.ts to route event lines (io/events-store.ts appendVerdictEvent); it is not a pair-hash ingredient (core/pair-hash.ts).' },
  { phrase: 'upgrading never turns a build red over law nobody changed', why: 'cli/init.ts takeUpTypeLaw writes ratification: true only when every enforced type rule was recorded (failed.length > 0 returns armed: false) and returns early once the type_law key exists; core/check-type-law.ts reports nothing unless ratification is true.' },
  // docs/family-contracts.md
  { phrase: '`yg pack list` asks the source for tags and never reads it', why: 'cli/pack.ts runList reads only the local record and asks each source for tags via FetchSession.versionsOf (ls-remote); readMarketplaceEntry, the only reader of yg-marketplace.yaml in pack, is called from add/update, not list.' },
  { phrase: 'Horde never reads `next.target`, and reads `next.remaining` only off', why: 'A claim about Horde, not the yg CLI: Horde\'s skills/horde/scripts/node.mjs reads next.remaining only in userOnlyRefusal/reviewerGap over READ_ONLY_CHECK (\'check --no-approve\') output and never reads next.target; Grain has no reader of either.' },
  // docs/feature-field.md
  { phrase: 'it never blocks a check, never fails a build', why: 'core/feature-index-write.ts: the index is never an issue, exit code or hash input, and a write failure is swallowed to the debug log.' },
  // docs/glossary.md
  { phrase: 'A script rule costs nothing; the reviewer may cost', why: 'A script rule runs its check.mjs locally with no provider call (core/fill-det.ts), and fill-writer.ts stamps no filledAt on a deterministic entry for that reason; \'cost\' here is the paid-call sense the entry defines.' },
  { phrase: 'elsewhere an uncovered warning that never blocks', why: 'core/check-coverage-tiers.ts buildCoverageAdvisoryIssue always builds \'uncovered-advisory\' with severity \'warning\' (registry: \'shown, never blocking\').' },
  { phrase: '`--only-deterministic` never records it.', why: 'core/fill-closing-phase.ts runClosingPhase calls applyPositiveClosure only when !onlyDeterministic, and the writer scope is \'deterministic\' (fill-writer.ts writeScope).' },
  // docs/model-swap-protocol.md
  { phrase: 'it never touches your lock or your telemetry', why: 'scripts/metamorphic.mjs runs yg aspect-test with cwd set to a mkdtemp fixture (buildFixture/judge), so any lock or event writes land in the throwaway directory, and aspect-test imports no lock writer.' },
  // docs/progressive-mode.md
  { phrase: 'and a block that names nothing at all (`progressive: {}`) are each', why: 'io/config-parser.ts rejects an empty progressive mapping and unknown keys, and filters progressive out of the yg-secrets overlay (line 705).' },
  { phrase: 'A fresh clone therefore never reads as "everything was already verified"', why: 'core/progressive-scope.ts burns \'cold pairs\' (no stored verdict) whose component reach is touched — \'reading that as everything is inherited would silently disarm the gate\' — and out-of-scope findings stay listed and counted as warnings.' },
  { phrase: 'on a change that reaches no reviewer rule, that is nothing at all', why: 'core/fill-classify.ts narrows only the paid half by the change scope and core/fill-dry-run.ts prices that same classification (reviewerCallBudget), so a change reaching no reviewer rule prices zero reviewer calls.' },
  { phrase: 'It therefore never records the point at which a component came up clean', why: 'core/fill-closing-phase.ts skips applyPositiveClosure under onlyDeterministic, so no source fingerprint or log baseline is recorded.' },
  // docs/reviewers.md
  { phrase: 'a diagnostic re-run that never writes the lock', why: 'cli/aspect-test.ts imports no lock writer (no writeLock/lock-store import); it appends only verdict events (io/events-store.ts appendVerdictEvent).' },
  { phrase: 'is an **infra-fail**: nothing is written to the lock, `callsMade` is 0', why: 'core/fill-llm.ts returns { kind: \'infra\', callsMade: 0 } for a failed assembly and the writer sets an entry only on a real verdict (fill-writer.ts \'an entry is written only on a REAL verdict\').' },
  { phrase: 'exits 0 for clean, 1 for violations, and never writes the lock', why: 'cli/aspect-test.ts imports no lock writer (no writeLock/lock-store import).' },
  { phrase: 'Changing a setting the rule never reads changes nothing.', why: 'core/pair-hash.ts folds a configuration value only as a \'config\' observation of a key the rule read, and a package rule\'s adaptation file is left out of the rule hash.' },
  { phrase: '`yg aspect-test` exits 1 if violations exist and never writes the lock', why: 'cli/aspect-test.ts imports no lock writer (no writeLock/lock-store import).' },
  { phrase: 'a missing corpus never blocks `yg check`', why: 'No yg check stage reads drill corpora; package-drills-missing is emitted only by core/marketplace-check.ts (yg marketplace check).' },
  { phrase: '`--aspect`, `--details`) never fills, and under CI (the `CI` variable set)', why: 'cli/check.ts resolveCheckMode forces { approve: false } whenever isTriageView (check-flags.ts) is true, before config or flags are consulted.' },
  { phrase: 'never touches the committed file — running it adds nothing', why: 'io/events-store.ts appendVerdictEvent routes to the committed stream only when committedLlm && source \'fill\' && kind \'llm\'; an --only-deterministic run fills no reviewer pair.' },
  { phrase: 'A failed write loses that record and never changes a fill\'s outcome', why: 'io/refused-store.ts storeRefusedContent wraps the write in try/catch and returns false; the fill\'s outcome does not depend on it.' },
  // docs/the-lock.md
  { phrase: 'and a triage view (`--top`, `--summary`, `--aspect`, `--details`) never fills.', why: 'cli/check.ts resolveCheckMode forces { approve: false } whenever isTriageView (check-flags.ts) is true.' },
  { phrase: 'held back: bare `yg check` fills nothing, not even script pairs', why: 'cli/check.ts resolveApproveMode returns read-only for auto_approve \'full\' when isCiEnvironment(env), and prints the \'auto-approve: full ignored — CI is set\' notice in resolveCheckMode.' },
  { phrase: 'Script verdicts never carry them: filling one costs nothing', why: 'core/fill-writer.ts setEntry stamps filledAt/filledSha only when pair.kind !== \'deterministic\'; a script fill makes no paid reviewer call.' },
  { phrase: 'bare `yg check` fills nothing, neither reviewer nor script pairs', why: 'cli/check.ts resolveApproveMode returns read-only for \'full\' under CI, and resolveCheckMode forces read-only for triage views.' },
  { phrase: 'An aspect refusal never blocks other nodes\' pairs.', why: 'The only refusal-driven skip is core/fill.ts detGateSkips, keyed on detGateKey of the pair\'s own component (or own file), so a refusal skips only that unit\'s reviewer pairs.' },
  { phrase: 'this run never records positive closure either', why: 'core/fill-closing-phase.ts skips applyPositiveClosure when onlyDeterministic.' },
  { phrase: '`yg check` warns — never blocks — on a reviewer key committed there', why: 'core/checks/credentials.ts emits all three codes with severity \'warning\' (registry agrees).' },
  { phrase: 'throwaway clone — it writes nothing to your repository but runs the code', why: 'cli/simulate.ts checks out and overlays only inside a mkdtemp clone with resolveYggRootWithinClone guarding escape, held by tests/e2e/simulate.e2e.test.ts \'... leaves the real tree byte-for-byte unchanged\'; the sentence already says the candidate code runs.' },
  { phrase: 'A triage view (`--top`, `--summary`, `--aspect`, `--details`) never fills and runs nothing.', why: 'cli/check.ts resolveCheckMode forces read-only for a triage view and runCheckRead passes runCompanionHooks: false; a plain read runs no check.mjs.' },
  { phrase: 'since `yg impact` never runs `companion.mjs`', why: 'cli/impact.ts and impact-handlers.ts import no hook runner and call no runCheck/verifyLock with runCompanionHooks (default false in core/check.ts and verify-lock.ts).' },
  { phrase: 'records no verdict there, so it never closes a cycle at all', why: 'core/fill-closing-phase.ts skips applyPositiveClosure under onlyDeterministic and the writer scope is \'deterministic\'.' },
  { phrase: 'the run records nothing over that node\'s code', why: 'core/fill-closure.ts applyPositiveClosure step (b) logGateBlocksNode skips a log_required node that owes an entry, so neither fingerprint nor baseline is recorded; it fills no pair of that node by definition.' },
  // source/cli/src/templates/knowledge/aspect-status.ts
  { phrase: 'status never changes a verdict\'s validity', why: 'core/pair-hash.ts excludes status from the pair hash (documented exclusion list) and core/verify-lock.ts classifies validity from the hash alone, never from status.' },
  { phrase: 'ONE exception to "advisory never blocks": the `prompt-too-large` assembly gate', why: 'core/check-pair-issues.ts emitPairIssue derives every pair issue\'s severity from pair.status except prompt-too-large (both the replacing and the valid-but-oversized case), which is always \'error\'.' },
  // source/cli/src/templates/knowledge/aspects-overview.ts
  { phrase: 'It never calls the reviewer and never runs `check.mjs`.', why: 'core/pairs.ts enumeration skips every aggregate aspect (isAggregateAspect → continue: no own reviewer, no own verdict), so a bundle yields no pair for any reviewer, script or companion to run on.' },
  { phrase: 'Status never changes a verdict\'s validity.', why: 'core/pair-hash.ts excludes status from the pair hash and core/verify-lock.ts decides validity from the hash, so no status flip can invalidate or validate a verdict.' },
  // source/cli/src/templates/knowledge/conditional-aspects.ts
  { phrase: 'raises `when-unmatched-port`, which never blocks `yg check`', why: 'utils/issue-code-registry.ts registers when-unmatched-port at severity \'warning\' and core/checks/aspects.ts emits it as \'warning\'; progressive rewriting only ever lowers severity and no code path promotes a warning.' },
  { phrase: 'when nothing at all applies — that fact stated plainly rather than left silent', why: 'cli/owner.ts states the \'nothing applies\' result explicitly for a type-matched file with no applicable rule (the same zero-enforcement classification core/type-visibility.ts uses), and when evaluation runs in core/when-evaluator.ts with no LLM call.' },
  // source/cli/src/templates/knowledge/log-management.ts
  { phrase: '`--only-deterministic` never writes the committed logs file', why: 'core/fill-writer.ts narrows writeScope to \'deterministic\' (the gitignored cache only) under onlyDeterministic, and core/fill-closing-phase.ts skips positive closure and passes writeLogs: false to recordAspectStatuses.' },
  // source/cli/src/templates/knowledge/onboarding.ts
  { phrase: 'An answer that changes nothing was a question you had', why: 'an instruction to the reader, not a claim about what the CLI does' },
  // source/cli/src/templates/knowledge/verification-and-lock.ts
  { phrase: 'it never reads or writes a lock entry, so it is never stale', why: 'core/check-lock-phase.ts emits relation-undeclared-dependency from the live relation pass result with no lock lookup, and relations/pass.ts\'s only cache is the content-addressed extractor-facts cache (never a verdict); the registry makes the code \'error\' and not suppressible.' },
  // source/cli/src/templates/knowledge/writing-llm-aspects.ts
  { phrase: 'A `per: node` aspect never runs on a type-covered file', why: 'core/pairs.ts nodeless enumeration skips every rule with scope.per !== \'file\' on a type-covered file and records the whole-unit-rule drop, so no pair (and no run) exists for it.' },
  { phrase: 'an advisory pair never blocks except a `prompt-too-large` one', why: 'core/check-pair-issues.ts emitPairIssue sets every pair issue\'s severity from pair.status except prompt-too-large, which is always \'error\', exactly the exception the sentence names.' },
  // source/cli/src/templates/rules.ts
  { phrase: 'it never touches the committed lock, your source, or your graph files', why: 'cli/check.ts runCheck takes the read path (runCheckRead, runCompanionHooks: false) unless resolveApproveMode says approve, and the lock writers (io/lock-store.ts writeLock/writeTypeLock) are called only from core/fill-writer.ts, fill-gc, log merge-resolve, type-log and migrations — never from the read path; the sentence itself names the gitignored caches it does write.' },
  { phrase: '`--approve` fills NOTHING that run (no pair on any node is verified)', why: 'core/fill.ts runFillHoldingLock calls runLogGatePhase (core/fill-log-gate.ts) before the deterministic and LLM phases, and it throws FillGatingError when any node owes an entry, so no pair is filled; held by tests/e2e/cli-log-gate-scope.test.ts \'a change to the component’s own source owes an entry, and the fill stops before recording anything\'.' },
  { phrase: 'A changed node the run fills nothing of does not stop it', why: 'the log gate is asked only of the nodes the run fills a pair of (core/fill-log-gate.ts runLogGatePhase over reportNodeSet), and core/fill-closure.ts skips a gate-blocked node so no fingerprint is recorded over it; held by tests/e2e/cli-log-gate-scope.test.ts \'a changed component the fill fills nothing of stays red but does not stop the fill\'.' },
  // source/cli/src/templates/schemas/aspect.ts
  { phrase: 'it NEVER changes the date itself and # never blocks a build', why: 'aspect-review-overdue is registered with severity \'warning\' in utils/issue-code-registry.ts and emitted by core/checks/aspect-contracts.ts, which only reads aspect.reviewBy; no CLI code writes review_by (it appears only in parser, checks, advise and marketplace-check).' },
  { phrase: 'companion pair is an upper bound (impact never runs companion.mjs)', why: 'core/impact-cost.ts counts a cold companion pair as \'cold-potential-companion\' without resolving it and imports no companion runner; verify-lock.ts runs a companion only under runCompanionHooks, which only the --approve fill passes.' },
  // source/cli/src/templates/schemas/config.ts
  { phrase: 'bare `yg check` fills nothing — no reviewer pair, no script', why: 'cli/check.ts resolveApproveMode returns approve:false for a config-driven full under CI, so runCheckFill is never reached; held by tests/unit/cli/resolve-approve-mode.test.ts \'config full + no flag + CI=true → read-only (no reviewer call from config in CI)\'.' },
  // review of sentences reworded by the policy's first pass
  { phrase: 'it never runs `check.mjs` or `companion.mjs`, makes no LLM call', why: 'cli/impact.ts, impact-handlers.ts and impact-cost.ts import no companion, script-runner or LLM code; the only writes are the opt-in debug log and the type-class cache, which the sentence does not deny.' },
  { phrase: 'it never reads or writes the lock, never calls a reviewer', why: 'cli/structure.ts imports no lock store and no reviewer or LLM code.' },
  { phrase: 'Never writes the lock |', why: 'cli/drill.ts imports no lock store: a drill writes only its events and drill results, never the lock.' },
];
